const copeBtns = ["Criticizing",
"Angry",
"Sarcastic",
"Aggressive",
"Grudgeful",
"Withdrawing",
"Self Shameful",
"Depressed",
"Anxious",
"Inconsolable",
"Exagerative",
"Self-Harmful",
"Performance Driven",
"Defensive",
"Demanding",
"Selfish",
"Obsessed",
"Irresponsible",
"Impulsive",
"Avoidant",
"Minimizing",
]

export default copeBtns