// 178 characters

export const quotes = [
    '"Priorities and purpose help keep us on track" -Candace Cameron Bure',
    '"The greatest gift you ever give is your honest self" -Mr.Rogers',
    '"You need the dark in order to show the light" -Bob Ross',
    '"Repitition creates the master" -Cesar Milan',
    '"I am worth it" -Yourself',
    '"We\'re all broken, that is how the light gets in. -Ernest Hemingway"',
    '"If you\'re going to be thinking, you may as well think big" -MLK Jr',
    '"Climate is what we expect, weather is what we get." -Mark Twain',
    '"The best way out is always through." -Robert Frost',
    '"Success is not final, failure is not fatal: it is the courage to continue that counts." - Winston Churchill',
    '"Failure means a stripping away of the inessential." -J.K. Rowling',
    '"Vitality shows in not only the ability to persist but the ability to start over." -F. Scott Fitzgerald',
    '"Keep your face to the sunshine and you cannot see the shadows." -Helen Keller',
    '"You cannot find peace by avoiding life." -Virginia Woolf',
    '"Be mindful to your thoughts - thoughts become actions" -Laozi',
    '"Let your dreams stay big and your worries stay small" -Rascall Flatts',
    '"Bless the broken road" -Rascal Flatts',
    '"If you quit once it becomes habit. Never quit!" -Michael Jordan',
    '"Change has to come for life to struggle forward." -Helen Hollick',
    '"kindness seeks to give without thought or condition of return." -Candace Cameron Bure',
    '"The present is theirs; the future, for which I really worked, is mine." -Nikola Tesla',
    '"The tragedy of life is what dies inside a man while he lives" -Albert Einstein',
    '"Life is a hypocrite if I can\'t live the way it moves me!" -John Eldredge',
    '"You can find that life - if you are willing to embark on a great adventure -John Eldredge"',
    '“Faithless is he that says farewell when the road darkens.” ― J.R.R. Tolkien',
    '"When we expose the lie, the enemy\'s power is broken." -Neil T. Anderson',
    '“It is never too late to be what you might have been.” -Mary Ann Evans',
    '"All truths are easy to understand once they are discovered; the point is to discover them." -Galileo Galilei',
    '"When you have nothing else have faith" -Francine Rivers',
    'If I have done the public any service, it is due to my patient thought. -Isaac Newton',
    '"We are products of our past, but we don\'t have to be prisoners of it." -Rick Warren',
    '"Act enthusiastic and you will be enthusiastic" -Dale Carnegie',
    '"If you\'re alive, there\'s a purpose for your life." -Rick Warren',
    '"You need to doubt your doubts and believe your beliefs." -Rick Warren',
    '"Although the world is full of suffering, it is also full of the overcoming of it." -Helen Keller',
    '"Don\'t let the things you can\'t do stop you from doing the things you can." -Mat Best',
    '"It is what we do after the fact that define us and puts us on the path to our next great success" -Nick Koumalatsos',
    '"Keeping calm, I think comes from the fact that you\'ve already analyzed the fire" -John Krebs',
    '"Peace begins with a smile" -Mother Teresa',
    '"I never quit, I never surrender, and I always move forward" -Nick Koumalatsos',
    '"Don\'t let your mind control you. Control your mind." -Jocko Willink',
    '"Our fatigue is often caused not by work, but by worry, frustration and resentment" -Dale Carnegie',
    '"Discipline equals freedom" -Jocko Willink',
    '"Adventures are never fun while you\'re having them." -C.S. Lewis',
    '"All battles are first won or lost, in the mind" -Joan of Arc',
    '"We are what we believe we are." - C.S. Lewis',
    '"I like to use the hard times in the past to motivate me today" -Dwayne Johnson',
    '"Opportunities multiply as they are seized." -Sun Tzu',
]